# Google Cloud Build configuration for DevDham Monitoring Service
# This file handles building and deploying Grafana to Cloud Run (PRODUCTION ONLY)

steps:
  # Validate Grafana configuration
  - name: 'gcr.io/cloud-builders/docker'
    args: ['run', '--rm', '-v', '/workspace:/workspace', 'alpine:latest', 'sh', '-c',
           'test -f /workspace/grafana/grafana.ini && test -f /workspace/grafana/Dockerfile && echo "✅ Configuration validated"']
    id: 'validate-config'

  # Build the Grafana Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '-t', 'gcr.io/$PROJECT_ID/grafana:$COMMIT_SHA',
      '-t', 'gcr.io/$PROJECT_ID/grafana:latest',
      './grafana'
    ]
    id: 'build-grafana'
    waitFor: ['validate-config']

  # Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/grafana:$COMMIT_SHA']
    id: 'push-grafana'
    waitFor: ['build-grafana']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/grafana:latest']
    id: 'push-grafana-latest'
    waitFor: ['build-grafana']

  # Deploy to Cloud Run (PRODUCTION ONLY)
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'grafana',
      '--image', 'gcr.io/$PROJECT_ID/grafana:$COMMIT_SHA',
      '--region', 'asia-south1',
      '--platform', 'managed',
      '--service-account', 'grafana-cloud-run@$PROJECT_ID.iam.gserviceaccount.com',
      '--add-cloudsql-instances', '$PROJECT_ID:asia-south1:grafana-db',
      '--memory', '1Gi',
      '--cpu', '1',
      '--min-instances', '0',
      '--max-instances', '5',
      '--port', '3000',
      '--allow-unauthenticated',
      '--set-env-vars', 'NODE_ENV=production',
      '--timeout', '300',
      '--concurrency', '80',
      '--execution-environment', 'gen2',
      '--cpu-throttling'
    ]
    id: 'deploy-grafana'
    waitFor: ['push-grafana']

  # Update traffic to new revision
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'services', 'update-traffic', 'grafana',
      '--to-latest',
      '--region', 'asia-south1'
    ]
    id: 'update-traffic'
    waitFor: ['deploy-grafana']

  # Verify Cloud SQL connectivity
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['sql', 'instances', 'describe', 'grafana-db', '--format=value(connectionName)']
    id: 'verify-cloudsql'
    waitFor: ['deploy-grafana']

  # Verify deployment health
  - name: 'gcr.io/cloud-builders/curl'
    args: [
      '-f', '-s', '--retry', '10', '--retry-delay', '15',
      'https://grafana-${_SERVICE_SUFFIX}.run.app/api/health'
    ]
    id: 'health-check'
    waitFor: ['update-traffic']

  # Additional Grafana-specific health checks
  - name: 'gcr.io/cloud-builders/curl'
    args: [
      '-s', '--retry', '3', '--retry-delay', '5',
      'https://grafana-${_SERVICE_SUFFIX}.run.app/login'
    ]
    id: 'grafana-login-check'
    waitFor: ['health-check']

# Build options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
  substitutionOption: ALLOW_LOOSE

# Build timeout
timeout: '1200s'

# Substitutions
substitutions:
  _SERVICE_SUFFIX: 'devdham'

# Artifacts to store
artifacts:
  images:
    - 'gcr.io/$PROJECT_ID/grafana:$COMMIT_SHA'
    - 'gcr.io/$PROJECT_ID/grafana:latest'

# Notification on build completion
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/slack-webhook/versions/latest
      env: 'SLACK_WEBHOOK'

# Tags for organization
tags:
  - 'monitoring'
  - 'grafana'
  - 'cloud-run'
  - 'devdham'
  - 'production-only'

# Build triggers configuration (to be set up separately):
# Production trigger:
#   - Branch: ^main$
#   - Variables: _SERVICE_SUFFIX=devdham
# NOTE: No development trigger - this service only deploys to production