apiVersion: 1

datasources:
  # Google Cloud Managed Prometheus datasource
  - name: Google Cloud Monitoring
    type: stackdriver
    access: proxy
    uid: google-cloud-monitoring
    isDefault: true
    jsonData:
      authenticationType: gce
      defaultProject: devdham-production-16
    secureJsonData: {}
    editable: true

  # Managed Prometheus via Google Cloud Monitoring API
  - name: Managed Prometheus
    type: prometheus
    access: proxy
    uid: managed-prometheus
    url: https://monitoring.googleapis.com/v1/projects/devdham-production-16/location/global/prometheus/api/v1
    isDefault: false
    jsonData:
      httpMethod: POST
      prometheusType: Prometheus
      prometheusVersion: 2.40.0
      customQueryParameters: ''
      timeInterval: 30s
      queryTimeout: 60s
      httpHeaderName1: 'Authorization'
    secureJsonData:
      httpHeaderValue1: 'Bearer $${GOOGLE_CLOUD_TOKEN}'
    editable: true

  # Local metrics endpoint for testing
  - name: Local Metrics
    type: prometheus
    access: proxy
    uid: local-metrics
    url: http://localhost:3001/api/v1/metrics
    isDefault: false
    jsonData:
      httpMethod: GET
      prometheusType: Prometheus
      prometheusVersion: 2.40.0
      timeInterval: 15s
      queryTimeout: 30s
    editable: true